# I have literally no idea what I'm doing, so I'll cargo cult hard.
# The below is copied and modified from: https://github.com/haskell-text/text-display/blob/main/.github/workflows/ci.yml

name: CI

on:
  pull_request:
    paths:
      - '*/src/**'
      - '*/*.cabal'
  push:
    branches:
      - 'master'
      - 'release-*'
    paths:
      - '*/src/**'
      - '*/*.cabal'

jobs:
  generate-matrix:
    name: "Generate matrix from cabal"
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    runs-on: ubuntu-latest
    steps:
      - name: Extract the tested GHC versions
        id: set-matrix
        uses: kleidukos/get-tested@v0.1.7.1
        with:
          cabal-file: example/pristine-example.cabal
          ubuntu-version: "latest"
          version: 0.1.7.1
  tests:
    name: ${{ matrix.ghc }} on ${{ matrix.os }}
    needs: generate-matrix
    runs-on: ${{ matrix.os }}
    strategy:
      matrix: ${{ fromJSON(needs.generate-matrix.outputs.matrix) }}
    steps:
      - name: Install system depedencies
        run: |
          sudo apt-get update
          sudo apt-get -y install libblas-dev liblapack-dev \
                                  libexpat1-dev libcairo2-dev libxdmcp-dev
      - name: Checkout base repo
        uses: actions/checkout@v4
      - name: Set up Haskell
        id: setup-haskell
        uses: haskell-actions/setup@v2
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: 'latest'
      - name: Freeze
        run: cabal freeze
      - name: Cache
        uses: actions/cache@v4.2.0
        with:
          path: ${{ steps.setup-haskell.outputs.cabal-store }}
          key: ${{ runner.os }}-ghc-${{ matrix.ghc }}-cabal-${{ hashFiles('**/plan.json') }}
          restore-keys: ${{ runner.os }}-ghc-${{ matrix.ghc }}-
      - name: Build
        run: |
          cabal configure --write-ghc-environment-files=always
          cabal build pristine
          cabal build pristine:sanity
          cabal build pristine-analysis
          cabal build pristine-vis-Chart
          cabal build pristine-example:example
